
const bodyDesc = [
  {"product_id":"7956275200235","ingramPartNumber":"5688919","xiaomiSku":"34167","body_html":"<br>• Historial de eventos\n<br>• Notificaciones sincronizadas con el smartphone\n<br>• Alerta de puerta abierta\n<br>• Ahora con sensor de luz <br>• Dimensiones del producto:34 x 32,7 x 14,5 mm\n<br>• Conectividad inalámbrica: Bluetooth 5.1 BLE\n<br>• Tipo de batería: CR2032 (instalada)\n<br>• Temperatura de funcionamiento: De -10 °C a 50 °C\n<br>• Humedad de funcionamiento: Del 0 al 95 % de humedad relativa (sin condensación)"}
  ,
  {"product_id":"7956275233003","ingramPartNumber":"5688907","xiaomiSku":"28990","body_html":"<br>• Instalación sencilla sin cables, monitorización de alta resolución\n<br>• Resistencia IP65 al polvo y al agua\n<br>• Amplio ángulo de visión de 130\n<br>• Batería con una duración de 90 días\n<br>• Detección de personas por medio de sensores infrarrojos pasivos<br>• Entrada nominal: 5 V, 2 A \n<br>• Dimensiones de la cámara externa:52,7 × 122 × 102,6 mm\n<br>• Peso neto de la cámara externa: 273 g   \n<br>• Ángulo de la lente: 130° \n<br>• Resolución: 1920 x 1080\n<br>• Apertura: f/2,1\n<br>• Codificación de vídeo: H.265\n<br>• Luces infrarrojas: 8 luces infrarrojas de 940 nm\n<br>• Temperatura de funcionamiento: De -20 °C a 50 °C\n<br>• Capacidad de la batería: 5700 mAh\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n de 2,4 GHz\n<br>• Compatible con Android 6.0 e iOS 10 o versiones posteriores\n<br>• Dimensiones del receptor de interior : 110 × 85 × 77,1 mm\n<br>• Peso neto del receptor de interior: 88 g\n<br>• Almacenamiento del receptor de interior \n<br>• Tarjeta microSD (hasta 32 GB)/unidad USB/almacenamiento en la nube\n<br>• Conexión del cable del receptor de interior\n<br>• Puerto: Ethernet RJ45\n<br>• Entrada nominal: 5 V, 2 A \n<br>• Dimensiones de la cámara externa: 52,7 × 122 × 102,6 mm\n<br>• Peso neto de la cámara externa: 273 g\n<br>• Ángulo de la lente: 130° \n<br>• Resolución: 1920 x 1080\n<br>• Apertura: f/2,1\n<br>• Codificación de vídeo: H.265\n<br>• Luces infrarrojas: 8 luces infrarrojas de 940 nm\n<br>• Temperatura de funcionamiento: De -20 °C a 50 °C\n<br>• Capacidad de la batería: 5700 mAh\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n de 2,4 GHz\n<br>• Compatible con: Android 6.0 e iOS 10 o versiones posteriores"}
  ,
  {"product_id":"7956275265771","ingramPartNumber":"5688896","xiaomiSku":"24270","body_html":"<br>• El diseño clásico que vuelve aún más avanzado\nCarga rápida de 18W \n<br>• Entrada/salida de doble puerto<br>• Tipo de batería: Batería de polímero de litio\n<br>• Capacidad de la batería: 37Wh, 3.7V (10000mAh)\n<br>• Capacidad nominal: 5500mAh (5.1V/2.6A)\n<br>• Puerto de entradaMicro-USB/USB-C\n<br>• Puertos de salida: USB-A x 2\n<br>• Entrada: 5V/2.1A, 9V/2.1A, 12V/1.5A (18W MAX)\n<br>• Salida:USB-A x1: 5V/2.4A, 9V/2.1A, 12V/1.5A (18W MAX)\nUSB-A x2: 5.1V/2.6A\n<br>• Tiempo de carga:- ~4 horas con un cargador de 9V/2A o 12V/1.5A - ~6 horas con un cargador de 5V/2A"}
  ,
  {"product_id":"7956275298539","ingramPartNumber":"5688936","xiaomiSku":"36266","body_html":"<br>• Hasta 40 dB*\n<br>• 3 modos ANC de anulación de ruido\n<br>• Modos de transparencia\n<br>• Diafragma dinámico supersensible\n<br>• Restaura los detalles del sonido de forma precisa\n<br>• Hasta 32 Horas de uración con el estuche de carga<br>• Peso neto del producto: 52 g\n<br>• Puerto de carga: Tipo C\n<br>• Impedancia del altavoz: 32 Ω\n<br>• Parámetros de entrada de los auriculares: 5 V⎓0,08 A\n<br>• Parámetros de entrada del estuche de carga: 5 V⎓0,5 A\n<br>• Parámetros de salida del estuche de carga: 5 V⎓0,2 A\n<br>• Conectividad inalámbrica: Bluetooth® 5.2\n<br>• Perfiles de Bluetooth: Bluetooth® de baja energía/HFP/A2DP/AVRCP\n<br>• Distancia de funcionamiento: 10 m (espacio abierto sin obstáculos)"}
  ,
  {"product_id":"7956275331307","ingramPartNumber":"5688941","xiaomiSku":"38949","body_html":"<br>• 55 km. Gran autonomía\n<br>• 25 km/h. Velocidad máx.\n<br>• 700 W. Potencia máx.\n<br>• 20 % Capacidad de ascensión*\n<br>• 10\" Con la tecnología Xiaomi DuraGel Tire. Neumático sin cámara con autosellante a prueba de pinchazos*\n<br>• 130 mm. Doble freno de disco\n<br>• Tamaño mejorado para una conducción más cómoda\n<br>• Puerto de carga y tapa magnéticos\n<br>• Cuerpo de aluminio ligero aeroespacial<br>• Velocidad máx.: 25 km/h (velocidad máx. para cada modo: Modo peatón: 6 km/h; D: 20 km/h; S: 25 km/h)\n<br>• Autonomía general: Aprox. 55 km*La autonomía se incrementará hasta los 55 km* mediante una actualización OTA que se lanzará en agosto. El nuevo firmware optimizará la eficiencia del motor para aumentar la autonomía.\n<br>• Peso: 17 kg\n<br>• Ángulo de subida máx: Aprox. 20\n<br>• Frenado: Sistema de frenado antibloqueo regenerativo E-ABS\n<br>• Freno de disco trasero de dos pastillas: \n<br>• Potencia nominal: 350 W\n<br>• Potencia máx.: 700 W\n<br>• Material de los neumáticos: Caucho natural, caucho sintético, resina y cable\n<br>• Carga máx.: 120 kg\n<br>• Altura del conductor: 120-200 cm\n<br>• Edad del conductor: De 16 a 50\n<br>• Temperatura de funcionamiento: -10~40 °C\n<br>• Temperatura de almacenamiento: -20~45 °C\n<br>• Clasificación IP: IPX4\n<br>• Tiempo de carga: Aprox. de 8 a 9 horas\n<br>• Modelo de batería: BCTA+71420-1701\n<br>• Capacidad nominal: 12 400 mAh/446 Wh\n<br>• Rango de temperatura de carga: 0~40 °C"}
  ,
  {"product_id":"7956275364075","ingramPartNumber":"5688900","xiaomiSku":"26552","body_html":"<br>• Carga Universal de 20W \n<br>• Bobinas dobles <br>• Compatible con carga rápida de 20W / <br>• Compatible con celulares que cuenten con carga inalambrica.\n<br>• Alto producto 109.7\n<br>• Ancho producto 91"}
  ,
  {"product_id":"7956275396843","ingramPartNumber":"5688902","xiaomiSku":"26923","body_html":"<br>• Puertos de entrada dual\n<br>• Puertos de salida dual\n<br>• 37 Wh de alta capacidad \n<br>• Batería de polímero de iones de litio de alta densidad<br>• Alimentación de la batería: 37 Wh, 3,7 V, 10.000 mAh\n<br>• Puertos de entrada: Micro-USB/USB-C\n<br>• Parámetros de entrada: 5 V/2.1 A\n<br>• Tipo de batería: Batería de polímero de iones de litio\n<br>• Capacidad nominal: 5500 mAh (5,1 V/2,6 A)\n<br>• Puertos de salida: 2 x USB-A\n<br>• Parámetros de salida: 5,1 V/2,4 A (salida de un solo puerto)\n5.1 V/2,6 A (salida de doble puerto)\n<br>• Dimensiones del producto: 150,5 x 73,6 x 15,1 mm"}
  ,
  {"product_id":"7956275429611","ingramPartNumber":"5688940","xiaomiSku":"38581","body_html":"<br>• Terapia de iones de agua doble\n<br>• Flujo de aire ultra alto de 20 m/s*\n<br>• Cuerpo de metal\n<br>• Control inteligente de la temperatura y modo de alternancia entre aire caliente y frío\n<br>• Boquilla magnética de dos capas\n<br>• Filtro de entrada de aire extraíble<br>• Modelo: CMJ03LX\n<br>• Tensión nominal: 220 V~\n<br>• Frecuencia nominal: 50-60 Hz\n<br>• Potencia nominal: 1800 W\n<br>• Longitud del cable de alimentación: 1,7 m\n<br>• Peso neto: 595 g (incluida la boquilla del concentrador)\n<br>• Dimensiones: 144 × 79 × 237 mm (incluida la boquilla del concentrador)"}
  ,
  {"product_id":"7956275462379","ingramPartNumber":"5688909","xiaomiSku":"30310","body_html":"<br>• Antena externa de 2x2 con cobertura Wi-Fi mejorada\n<br>• 300 Mbps versión de alta potencia \n<br>• Soporta hasta 24 dispositivos conectados de forma simultánea<br>• Dimensiones: 80 x 54 x 70 mm\n<br>• CPU: MT7628K 580 MHz\n<br>• ROM:2 MB\n<br>• RAM:8 MB\n<br>• Tipo de antena:2 antenas externas\n<br>• Estándares inalámbricos:JEEE 802.11b/g/n\n<br>• Ritmo de la señal:2,4 GHz, hasta 300 Mbps\n<br>• Canal de 2.4 GHZ: 1,2,3,...,13\n<br>• Seguridad inalámbrica:Cifrado WPA-PSK/ WPA2-PSK\n<br>• Fuente de alimentación:100-240 V/0.35 A"}
  ,
  {"product_id":"7956275495147","ingramPartNumber":"5688772","xiaomiSku":"16084","body_html":"<br>• El soporte del teléfono gira 360º\n<br>• Mando a distancia bluetooth separado\n<br>• Almohadilla antideslizante.<br>• Estámdares: Q / YDS 001-2015.\n<br>• Para Android4.3 o posterior.\n<br>• Para iOS5.0 o posterior.\n<br>• Puerto:Micro USB.\n<br>• Dimensiones:45 mm. x 49,5 mm. x 190 mm. (tolerancias de +/- 2,0 mm.)\n<br>• Peso neto:155 g.\n<br>• Peso bruto:178 g.\n<br>• Bluetooth:Bluetooth 3.0."}
  ,
  {"product_id":"7956275560683","ingramPartNumber":"5688773","xiaomiSku":"21907","body_html":"<br>• Chip BIA de alta precisión\n<br>• 13 métricas de composición corporal\n<br>• Prueba de equilibrio\n<br>• Capaz de detectar cambios de peso tan pequeños como 50g<br>• Dimensiones: 300 x 300 x 25 mm\n<br>• Unidades de pesaje: Jin/kg/lb\n<br>• Material externo: Cristal reforzado + plástico de ingeniería ABS\n<br>• Temperatura de funcionamiento: Entre 0 °C y 40 °C\n<br>• Peso: 1,7 kg\n<br>• Rango de medición: De 100 g a 150 kg\n<br>• División mínima de la báscula: 50 g\n<br>• Conexión inalámbrica: Bluetooth 5.0\n<br>• Fuente de alimentación: Cuatro baterías AAA de 1,5 V\n<br>• Requisitos del dispositivo: Se ejecuta en dispositivos que utilicen Android 4.4/iOS 9.0 o versiones posteriores (iPhone 5s o posterior) y que admitan Bluetooth 4.0 o posterior"}
  ,
  {"product_id":"7956275593451","ingramPartNumber":"5688949","xiaomiSku":"40590","body_html":"<br>• Fuente de agua circulante\n<br>•  Filtrado en 4 etapas \n<br>• Funcionamiento silencioso \n<br>• Conexión doméstica inteligente<br>• Temperatura de funcionamiento: 4 a 40 °C\n<br>• Entrada: 5,9 V⎓1,0 A5,9 V⎓1,0 A5,9 V⎓1,0 A\n<br>• Humedad de funcionamiento: Del 10 % al 90 % de humedad relativa\n<br>• Potencia nominal: 5,9 W\n<br>• Longitud del cable de alimentación: 1,5 m\n<br>• Dimensiones del producto: 191 x 191 x 177 mm\n<br>• Capacidad: 2 L"}
  ,
  {"product_id":"7956275626219","ingramPartNumber":"5688944","xiaomiSku":"39481","body_html":"<br>• Picado multiángulo con 8 cuchillas\n<br>• Doble modo de mezcla en frío y en caliente\n9 velocidades ajustables\n<br>• Hasta 4 horas de aislamiento en modo de conservación del calor\n<br>• Recetas rápidas online<br>• Tensión nominal: 220-240 V~\n<br>• Frecuencia nominal: 50/60 Hz\n<br>• Potencia de mezclado: 1000 W\n<br>• Potencia de calentamiento: 800-950 W\n<br>• Capacidad máxima para bebidas frías: 1600 ml\n<br>• Capacidad máxima para bebidas calientes: 1200 ml\n<br>• Dimensiones del producto: 188 x 222 x 436 mm\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n de 2,4 GHz"}
  ,
  {"product_id":"7956275658987","ingramPartNumber":"5688937","xiaomiSku":"36607","body_html":"<br>• Llamada telefónica por Bluetooth®\n<br>• Pantalla AMOLED de 1,43''\n<br>• Cristal de zafiro Caja de acero inoxidable con <br>• Correa de cuero\n<br>• Monitorización durante todo el día de la frecuencia cardiaca y el SpO₂\n<br>• Carga inalámbrica<br>• Materiales: Cristal de zafiro y caja de acero inoxidable\n<br>• Material de la correa: Cuero de becerro/fluorocarbono\n<br>• Color del producto: Negro (correa de cuero negra + correa de fluorocarbono negra); plateado (correa de cuero marrón + correa de fluorocarbono gris)\n<br>• Dimensiones del producto: 46,5 x 46,5 x 11 mm (sin incluir la correa ni los salientes del contorno)\n<br>• Pantalla: Pantalla AMOLED de 1,43''\n<br>• Resolución de pantalla: 466 x 466\n<br>• Correa de longitud ajustable: 165,1-225,1 mm (cuero); 149,8-233,8 mm (fluorocarbono)\n<br>• Capacidad de la batería: 470 mAh\n<br>• Tipo de batería: Batería de polímero de iones de litio\n<br>• Temperatura de funcionamiento: De -10 °C a 45 °C\n<br>• Clasificación de resistencia al agua: 5 ATM\n<br>• Estándares aplicados: GB/T 30106-2013\n<br>• Sensores: Sensor de frecuencia cardiaca (con sensor de oxígeno en sangre), acelerómetro, giroscopio, sensor geomagnético, sensor atmosférico y sensor de luz ambiental\n<br>• Puerto de carga: Carga inalámbrica\nCompatible con Android 6.0 e iOS 10.0 o versiones posteriores\n<br>• Sistemas de posicionamiento por satélite: GPS, BeiDou, GLONASS, Galileo, QZSS\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n 2,4 GHz; Bluetooth® 5.2"}
  ,
  {"product_id":"7956275691755","ingramPartNumber":"5688929","xiaomiSku":"35792","body_html":"<br>• Cuerpo de aleación de aluminio\n<br>• Manillar minimalista + combinación atractiva de colores\n<br>• Velocidad máxima de 25 km/h*.Rendimiento de conducción potente\n<br>• Autonomía de 20 km*.Domina fácilmente las distancias cortas\n<br>• Sube pendientes de hasta un 14 %*. Afronta sin esfuerzo distintas condiciones de la carretera. <br>• Potencia nominal: 300 W\n<br>• Dimensiones: 1105 x 430 x 1137 mm\n<br>• Peso neto del vehículo: Aprox. 13 kg\n<br>• Dimensiones (plegado): 1104 x 429 x 484 mm\n<br>• Carga máxima: 100 kg\n<br>• Edad aplicable: De 16 a 50 años\n<br>• Altura aplicable: De 120 a 200 cm\n<br>• Velocidad máxima:25 km/h\n<br>• Autonomía máxima: Aprox. 20 km\n<br>• Capacidad máxima de subida de pendientes: Aprox. 14 %\n<br>• Grado de protección IP: IPX4\n<br>• Tiempo de carga: Aprox. 4,5 horas\n<br>• Tensión nominal: 36 V\n<br>• Tensión de carga máxima: 42 V\n<br>• Energía nominal: 187 Wh\n<br>• Capacidad nominal: 5,2 Ah\n<br>• Rango de temperatura de funcionamiento: De 0 ℃ a 40 ℃\n<br>• Peso neto del vehículo: Aprox. 13 kg"}
  ,
  {"product_id":"7956275724523","ingramPartNumber":"5688930","xiaomiSku":"35847","body_html":"<br>• Reproductor portatil de contenidos streaming | Desarrollado en Android TV\n<br>• Con Google Assistant y Smart Cast | Sonido envolvente Dolby y DTS<br>• Dimensiones.Longitud 92.4mm,Peso 28.5g, Anchura 30.2mm\n<br>• Color:Negro\n<br>• Grosor:15.2mm\n<br>• Resolución de salida: 1080P (1920x1080@60fps)\n<br>• RAM: 1GB\n<br>• CPU: Cortex-A53 de cuatro núcleos\n<br>• Almacenamiento: 8GB\n<br>• GPU: ARM Mali-450\n<br>• Sistema operativo: Android 9.0\n<br>• Puertos: x1 HDMI, x1 Micro USB"}
  ,
  {"product_id":"7956275757291","ingramPartNumber":"5688946","xiaomiSku":"39873","body_html":"<br>• Pantalla AMOLED de alta resolución de 1,62\"\n<br>• Monitorización del SpO₂ durante todo el día\n<br>• Análisis de entrenamiento profesional con VO₂ máx\n<br>• Monitorización de la frecuencia cardiaca\n<br>• Resistencia al agua de 5 ATM\n<br>• Batería con una duración de 14 días<br>• Dimensiones: 46,5 mm x 20,7 mm x 12,25 mn\n<br>• Peso: 13,5 g\n<br>• Tamaño: 160-224 mm\n<br>• Material: TPU\n<br>• Hebilla de la pulsera: aleación de aluminio\n<br>• Pantalla táctil AMOLED de 1,62\"\n<br>• Resolución: 192 x 490 píxeles, 326 ppp\n<br>• Brillo: hasta 500 nits, ajustable\n<br>• Cristal templado con revestimiento antihuellas\n<br>• Diseños de pantalla: más de 100\n<br>• Sensor de 6 ejes de alta precisión y sensor de frecuencia cardiaca PPG: Acelerómetro de 3 ejes de bajo consumo y giroscopio de 3 ejes\n<br>• Sensor de frecuencia cardiaca PPG\n<br>• Tipo de carga: carga magnética\n<br>• Tiempo de carga: ≤2 horas\n<br>• Tiempo de uso típico: ≥14 días\n<br>• Capacidad: 180 mAh\n<br>• Más de 110 modos deportivos\n<br>• Monitorización de la frecuencia cardiaca\n<br>• Seguimiento del SpO₂\n<br>• Resistencia al agua de 5 ATM*\n<br>• Bluetooth 5.2 BLE\n<br>• Sistema operativo: Android 6.0 o versiones posteriores; iOS 10 o versiones posteriores"}
  ,
  {"product_id":"7956275790059","ingramPartNumber":"5688931","xiaomiSku":"35912","body_html":"<br>• Pantalla táctil a color de 1,55\"\n<br>• Resistencia al agua 5 ATM\n<br>• Medición del SpO₂* y monitor de frecuencia cardiaca continuo\n<br>• GPS independiente multisistema\n<br>• Hasta 10 días de duración de la batería<br>• Altura: 41,2 mmAnchura: 35,3 mmGrosor: 10,7 mmPeso neto: 35 g (incluida la correa)\nColor: Marfil, Negro, Azul, Rosa, Oliva, Marrón\n<br>• Longitud ajustable: 140-210 mmMaterial: TPU\n<br>• Pantalla TFT (transistor de película fina) cuadrada de 1,55\"Resolución:  320 × 360\n<br>• Sensor óptico de frecuencia cardiaca, acelerómetro, giroscopio y brújula electrónica GPS/GLONASS/Galileo/BeiDou\n<br>• Batería: 262 mAh Puerto de carga: carga magnéticaDuración de la batería: 10 días en modo de uso normal*\n5 días en modo de uso intensivo*\n<br>• Nivel de resistencia al agua: 5 ATM*Conectividad inalámbrica: Bluetooth 5.0 (Bluetooth de baja energía)Sistemas compatibles: Android 6.0 o versiones posteriores\niOS 10.0 o versiones posteriores"}
  ,
  {"product_id":"7956275822827","ingramPartNumber":"5688932","xiaomiSku":"35915","body_html":"<br>• Pantalla táctil a color de 1,55\"\n<br>• Resistencia al agua 5 ATM\n<br>• Medición del SpO₂* y monitor de frecuencia cardiaca continuo\n<br>• GPS independiente multisistema\n<br>• Hasta 10 días de duración de la batería<br>• Altura: 41,2 mmAnchura: 35,3 mmGrosor: 10,7 mmPeso neto: 35 g (incluida la correa)\nColor: Marfil, Negro, Azul, Rosa, Oliva, Marrón\n<br>• Longitud ajustable: 140-210 mmMaterial: TPU\n<br>• Pantalla TFT (transistor de película fina) cuadrada de 1,55\"Resolución:  320 × 360\n<br>• Sensor óptico de frecuencia cardiaca, acelerómetro, giroscopio y brújula electrónica GPS/GLONASS/Galileo/BeiDou\n<br>• Batería: 262 mAh Puerto de carga: carga magnéticaDuración de la batería: 10 días en modo de uso normal*\n5 días en modo de uso intensivo*\n<br>• Nivel de resistencia al agua: 5 ATM*Conectividad inalámbrica: Bluetooth 5.0 (Bluetooth de baja energía)Sistemas compatibles: Android 6.0 o versiones posteriores\niOS 10.0 o versiones posteriores"}
  ,
  {"product_id":"7956275855595","ingramPartNumber":"5688925","xiaomiSku":"35115","body_html":"<br>• Inflado rápido, rendimiento óptimo\n<br>• Potente y Compacto\n<br>• Cinco modos de inflado\n<br>• Aumento del rendimiento de inflado en un 45,40%<br>• Dimensiones: 124 x 71 x 45,3 mm (compresor de aire, sin manguera de aire)\nIntervalo de presión de inflado\n0,2 a 10,3 bares/3 a 150 psi\n<br>• Temperatura de funcionamiento\nCarga: De 0 ℃ a 45 ℃. Descarga: De -10 ℃ a 45 ℃\n<br>• Temperatura de almacenamiento: De -10 ℃ a 45 ℃\n<br>• Capacidad de la batería: 14,8 Wh\n<br>• Valor de ruido durante el funcionamiento: Menos de 80 dB a 1 m de distancia\n<br>• Parámetros de entrada: 5 V ⎓ 2 A\n<br>• Puerto de carga: Tipo C\n<br>• Tiempo de carga: Menos de 3 h"}
  ,
  {"product_id":"7956275888363","ingramPartNumber":"5688923","xiaomiSku":"34484","body_html":"<br>• Navegación por giroscopio y con ayuda visual\n<br>• Captura precisa del diseño de tu casa\n<br>• 25 sensores de alta precisión\n<br>• Percepción aguda de entornos complejos\n<br>• Aspiración potente de 2200 Pa\n<br>• Elimina fácilmente la suciedad de los pisos\n<br>• Depósito de polvo de gran capacidad de 450 mLUnidad Principal:\n<br>• Dimensiones: 353 × 81.3 mm\n<br>• Rated Power: 35 W\n<br>• Rated Voltage: 14.4 V⎓\n<br>• Net Weight: 3.1 kg\n<br>• Battery Capacity: 2500 mAh ( rated capacity )\n<br>• 2600 mAh ( nominal capacity )\nEstación de carga:\n<br>• Rated Input: 100–240 V ~ 50/60 Hz 0.6 A\n<br>• Rated Output: 20 V⎓ 1.2 A\n<br>• Item Dimensions: 150 × 135 × 97.4 mm"}
  ,
  {"product_id":"7956275921131","ingramPartNumber":"5688927","xiaomiSku":"35756","body_html":"<br>• Experiencia inalámbrica ultrarrápida Wi-Fi 6 de 3202 Mbps\n<br>• Compatibilidad con red de malla: Cobertura Wi-Fi 6 perfecta para toda la casa\n<br>• Compatibilidad con MU-MIMO 4 x 4\n<br>• OFDMA: Transmisión en varios dispositivos con menos congestión<br>• Dimensiones: L. × An. × Al. (por unidad) 284 mm × 186 mm × 186 mm\n<br>• Color del producto: Negro\n<br>• Procesador: CPU MediaTek Filogic800 A53 de doble núcleo a 1,35 GHz\n<br>• Memoria: 256 MB\n<br>• Wi-Fi 2,4 GHz: 4 x 4 (admite hasta el protocolo IEEE 802.11n; la velocidad máxima teórica es de 800 Mbps)\n<br>• Wi-Fi 5 GHz: 4 x 4 (admite hasta el protocolo IEEE 802.11ax; la velocidad máxima teórica es de 2402 Mbps)\n<br>• Antenas: Antenas omnidireccionales externas\n<br>• Total de puertos: 1 puerto WAN adaptable 10/100/1000 Mbps (Auto MDI/MDIX) 3 puertos LAN adaptables 10/100/1000 Mbps (Auto MDI/MDIX)\n<br>• Luz indicadora LED: 2 luces: 1 indicador del sistema y 1 indicador de Internet\n<br>• Botón de restablecimiento del sistema: 1\n<br>• Botón de red de malla: 1\n<br>• Puerto de entrada de alimentación: 1\nEstándares de protocolo: IEEE 802.11a/b/g/n/ac/ax, IEEE 802.3/3u/3ab"}
  ,
  {"product_id":"7956275953899","ingramPartNumber":"5688943","xiaomiSku":"39191","body_html":"<br>• 1.7L de alta capacidad\n<br>• Asa vertical integrada\n<br>• 100% libre de BPA\n<br>• Aislamiento térmico de doble capa\n<br>• 4 soluciones de seguridad eléctrica<br>• Rated voltage: 220V-240V\n<br>• Rated frequency: 50-60Hz\n<br>• Product dimensions: 227 x 158 x 262mm\n<br>• Rated power: 1800W\n<br>• Volume: 1.7L\n<br>• Product weight: 1.2kg"}
  ,
  {"product_id":"7956275986667","ingramPartNumber":"5688908","xiaomiSku":"29048","body_html":"<br>• Con calidad de imagen 2K supernítida e IA actualizada\n<br>• 3 megapíxeles\n<br>• Gran apertura f/1,4\n<br>• Imagen a todo color en condiciones de baja iluminación\n<br>• Detección de personas por medio de IA\n<br>• Peso neto del producto: 310 g\n<br>• Número de modelo del producto: MJSXJ09CM\n<br>• Entrada de alimentación:5 V = 2 A\n<br>• Temperatura de funcionamiento: De -10 °C a 50 °C\n<br>• Apertura: f/1,4\n<br>• Ángulo de la lente: 110°\n<br>• Resolución: 2304 x 1296\n<br>• Dimensiones del producto: 115 × 78 × 78 mm\n<br>• Codificación de vídeo: H.265\n<br>• Compatible con\nAndroid 4.4 e iOS 9.0 o versiones posteriores\n<br>• Almacenamiento: Tarjeta microSD (compatibilidad con tarjetas de hasta 32 GB)\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n de 2,4 GHz"}
  ,
  {"product_id":"7956276019435","ingramPartNumber":"5688939","xiaomiSku":"38561","body_html":"<br>• Anulación de ruido activa híbrida de hasta 35 dB*\n<br>• 3 opciones de nivel de ANC y modo ANC adaptativo\n<br>• Reducción de ruido por IA\n<br>• Modo de transparencia doble\n<br>• Unidad de diafragma dinámico de 10 mm, diafragma ultrafino de 0,006 mm\n<br>• Hasta 30 horas de batería con estuche<br>• Parámetros de entrada de los auriculares: 5 V ⎓ 100 mA\n<br>• Parámetros de entrada del estuche de carga: 5 V ⎓ 450 mA\n<br>• Conectividad inalámbrica: Bluetooth® 5.2\n<br>• Peso neto de un solo auricular: Aprox. 4,5 g\n<br>• Peso total con el estuche de carga: Aprox. 55 g\n<br>• Puerto de carga: Tipo C\n<br>• Impedancia del altavoz: 16 Ω±15 %"}
  ,
  {"product_id":"7956276052203","ingramPartNumber":"5688948","xiaomiSku":"40586","body_html":"<br>• Alimentación automática\n<br>• Impermeable y fresco\n<br>• Dispensación regulada\n<br>• Conexión inteligente\n<br>• Color del producto: blanco\n<br>• Entrada5,9 V⎓1,0 A\n<br>• Potencia nominal: 5,9 W\n<br>• Dimensiones del producto: 311 x 180 x 387 mm\n<br>• Capacidad: 3,6 L\n<br>• Peso neto: 3 kg\n<br>• Longitud del cable de alimentación: 1,5 m"}
  ,
  {"product_id":"7956276084971","ingramPartNumber":"5688904","xiaomiSku":"28309","body_html":"<br>• Calidad de imagen 2K supernítida, IA actualizada\n<br>• 3 millones de píxeles\n<br>• Imagen panorámica de 360°Imagen a todo color en condiciones de baja iluminación\n<br>• Detección de personas por medio de IA\n<br>• Reducción de ruido con micrófono dual\n<br>• Conexión Wi-Fi de doble Banda<br>• Peso neto del producto: 349 g\n<br>• Número de modelo del producto: MJSXJ06CM\n<br>• Entrada de alimentación: 5 V = 2 A\n<br>• Temperatura de funcionamiento: -10 °C a 50 °C\n<br>• Ángulo de la lente: 110°\n<br>• Resolución: 1296p\n<br>• Dimensiones del producto: 122 × 78 × 78 mm\n<br>• Codificación de vídeo: H.265\n<br>• Sistemas compatibles:Android 4.4 e iOS 9.0 o versiones posteriores\n<br>• Almacenamiento: Tarjeta microSD (compatibilidad con tarjetas de hasta 32 GB)\n<br>• Estándar aplicado: Q31/0115000198C009-2018-01\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11a/b/g/n/ac 2,4 Ghz/5 GHz, Bluetooth 4.2"}
  ,
  {"product_id":"7956276117739","ingramPartNumber":"5688912","xiaomiSku":"30807","body_html":"Viaja hasta 30 km de distancia\nVelocidad máxima de 25 km/h\nPotencia máxima de 600 W\nNuevo freno de disco trasero de dos pastillas\nPlegado en 3 pasos\nCuerpo de aluminio de grado aeroespacial<br>• Velocidad máx: 25 km/h (velocidad máx. para cada modo: Modo peatón: 5 km/h; D: 20 km/h; S: 25 km/h)\n<br>• Alcance: 30 km\n<br>• Peso: 13,2 kg\n<br>• Capacidad de ascensión: 16 %\n<br>• Frenado: eABS + freno de disco trasero de dos pastillas\n<br>• Potencia nominal: 300 W\n<br>• Potencia máx: 600 W\n<br>• Neumáticos: Ruedas neumáticas delanteras y traseras de 8,5\"\n<br>• Protección por subtensióndel controlador: 29 V ± 0,5 V\n<br>• Límite de corriente del controlador: 17 A ± 0,5 A\n<br>• Tipo de motor: Motor CC sin escobillas\n<br>• Carga máx.: 100 kg\n<br>• Altura del conductor: 120 cm-200 cm\n<br>• Edad del conductor: De 18 a 50\n<br>• Temperatura de funcionamiento: -10 °C~40 °C\n<br>• Temperatura de almacenamiento: -20 °C~45 °C\n<br>• Clasificación IP: IP54\n<br>• Tiempo de carga: 5,5 horas\n<br>• Batería de iones de litio\n<br>• Modelo de batería: NE1003-H\n<br>• Capacidad nominal: 7650 mAh/275 Wh\n<br>• Tensión nominal: 36 V de CC\n<br>• Máxima potenciade carga: 42 V de CC\n<br>• Rango de temperaturade carga: 0 °C ~ +40 °C\n<br>• Rango de temperaturade descarga: -20 °C ~ +50 °C\n<br>• Peso de la batería: 1,6 kg\n<br>• Vida útil cíclica: 500 ciclos de carga con alimentación mantenida por encima del 70 %\n<br>• Potencia de salida: 71 W\n<br>• Corriente de entrada: 2 A máx.\n<br>• Corriente de salida: 1,7 A\n<br>• Tensión de entrada: 100-240 V de CA\n<br>• Tensión máx. de salida: 42 V de CC\n<br>• Longitud del cable de CC: 2 m\n<br>• Tipo de puerto del cable de CC: Personalizado de Φ 8 x 1,6 mm"}
  ,
  {"product_id":"7956276150507","ingramPartNumber":"5688910","xiaomiSku":"30510","body_html":"<br>• 600 W Máxima potencia\n<br>• 45 km Súper largo alcance\n<br>• 25 km/h velocidad máxima\n<br>• 3 Segundos Plegado rápido\n<br>• 8.5‘’ Ruedas neumáticas y Cuerpo de aluminio aeroespacial\n<br>• E-ABS + discos de freno<br>• Velocidad máxima: 25 km/h (Velocidad máxima para cada modo:\n<br>• Modo peatonal:5 km/h; D: 20 km/h; S: 25 km/h)\n<br>• Rango:45 km.\n<br>• Peso: 14,2 kg\n<br>• Gradeabilidad: m20%\n<br>• Frenado: E-ABS y freno de disco\n<br>• Potencia nominal: 300 W\n<br>• Potencia máxima: 600 W\n<br>• Neumáticos: Neumáticos delanteros y traseros de 8.5\".\n<br>• Protección de subtensión del controlador: 29V±0.5V\n<br>• Límite de corriente del controlador: 17A±0.5A\n<br>• Tipo de motor: Motor de corriente continua sin cepillo\n<br>• Carga máxima: 100 kg.\n<br>• Altura del usuario: 120cm-200cm\n<br>• Edad del usuario: De 16 a 50 años\n<br>• Temperatura de trabajo: -10°C a 40°C\n<br>• Temperatura de almacenamiento: -20°C a 45°C\n<br>• Clasificación IP: IP54\n<br>• Tiempo de carga: 8-9 horas \n<br>• Tipo de batería: Batería de iones de litio\n<br>• Modelo de batería: NED1004-K\n<br>• Capacidad nominal: 12400 mAh/ 446 Wh\n<br>• Voltaje nominal: 37 VDC\n<br>• Máximo voltaje de carga: 42 VDC\n<br>• Rango de temperatura de carga: 0℃~+40℃\n<br>• Rango de temperatura de descarga: -20℃~+50℃\n<br>• El peso de la batería: 3 kg.\n<br>• Vida cíclica: 500 ciclos de carga con\nuna potencia mantenida\npor encima del 70%\n<br>• Potencia de salida: 71 W\n<br>• Corriente de entrada: 2 A MAX: Corriente de salida: 1.7A\n<br>• Voltaje de entrada: 100-240VAC 50/60Hz\n<br>• Voltaje de salida: 42 V\n<br>• Longitud del cable DC: 2m\n<br>• Tipo de puerto de cable DC: \n<br>• Personalizado Φ8.0*1.6mm"}
  ,
  {"product_id":"7956276183275","ingramPartNumber":"5688933","xiaomiSku":"36103","body_html":"<br>• Batería de hasta 18 horas de duración\n<br>• Bluetooth® 5.2\n<br>• Resistencia IP54* al polvo y al agua<br>• Conectividad inalámbrica: Bluetooth® 5.2\n<br>• Alcance de comunicación: 10 m (espacio abierto sin obstáculos)\n<br>• Peso neto de un solo auricular: Aprox. 4,2 g\n<br>• Peso total con el estuche de carga: Aprox. 36 g\n<br>• Duración de la batería de los auriculares: Aprox. 5 horas\n<br>• Duración de la batería del estuche de carga: Aprox. 18 horas\n<br>• Dimensiones de los auriculares: 24,5 x 16,7 x 24,6 mm\n<br>• Dimensiones del estuche de carga: 60 x 46 x 23,7 mm\n<br>• Puerto de carga: Tipo C"}
  ,
  {"product_id":"7956276216043","ingramPartNumber":"5688934","xiaomiSku":"36104","body_html":"<br>• Batería de hasta 18 horas de duración\n<br>• Bluetooth® 5.2\n<br>• Resistencia IP54* al polvo y al agua<br>• Conectividad inalámbrica: Bluetooth® 5.2\n<br>• Alcance de comunicación: 10 m (espacio abierto sin obstáculos)\n<br>• Peso neto de un solo auricular: Aprox. 4,2 g\n<br>• Peso total con el estuche de carga: Aprox. 36 g\n<br>• Duración de la batería de los auriculares: Aprox. 5 horas\n<br>• Duración de la batería del estuche de carga: Aprox. 18 horas\n<br>• Dimensiones de los auriculares: 24,5 x 16,7 x 24,6 mm\n<br>• Dimensiones del estuche de carga: 60 x 46 x 23,7 mm\n<br>• Puerto de carga: Tipo C"}
  ,
  {"product_id":"7956276248811","ingramPartNumber":"5688935","xiaomiSku":"36251","body_html":"<br>• Succión de hasta 185 AW\n<br>• Cabezal de limpieza multisuperficie\n<br>• Tecnología antienredos \n<br>• Ajuste smart del poder de succión\n<br>• Batería de polímero de iones de litio de alta capacidad<br>• Dimensiones de la aspiradora: 341,5 × 100 × 266,5 mm\n<br>• Peso neto de la aspiradora: Aprox. 1,6 kg\n<br>• Capacidad del compartimento de polvo: Aprox. 0,3 L máx.\n<br>• Tensión nominal: 22,2 V ⎓\n<br>• Potencia nominal: 500 W"}
  ,
  {"product_id":"7956276281579","ingramPartNumber":"5688947","xiaomiSku":"40033","body_html":"<br>• Hasta 67 W de potencia de salida\n<br>• ncluye un cable de carga<br>• Tipo de puerto: USB-A a tipo C\n<br>• Parámetros de entrada: 100-240 V~, 50/60 Hz, 1,7A\n<br>• Parámetros de salida: 5 V⎓3 A / 5-20 V⎓6,2-3,25 A (67 W máx.)\n<br>• Dimensiones: 55,9 × 49,3 × 28 mm (longitud de la clavija no incluida)\n<br>• Temperatura de funcionamiento:-10~40 °C"}
  ,
  {"product_id":"7956276314347","ingramPartNumber":"5688918","xiaomiSku":"34108","body_html":"<br>• Carga rápida máx. de 50 W \n<br>• Salida de tres puertos\n<br>• Batería de iones de litio de gran calidad y alta potencia de 74 Wh\n<br>• Carga rápida bidireccional de tipo C\n<br>• Permite cargar tres dispositivos a la vez\n<br>• Compatible con la carga de baja corriente<br>• Tipo de batería: Batería de polímero de iones de litio\n<br>• Potencia de la batería: 74 Wh, 3,7 V, 20 000 mAh\n<br>• Capacidad nominal: 12 000 mAh (5 V/4 A)\n<br>• Puerto de entrada: Tipo C\n<br>• Puerto de salida: USB A/tipo C\n<br>• Parámetros de entrada: 5 V⎓3 A, 9 V⎓3 A, 12 V⎓3 A, 15 V⎓3 A, 20 V⎓2,25 A\n<br>• Parámetros de salida: 50 W máx.\n<br>• Aproximadamente 11 horas (con cargador de 5 V/2 A)\n<br>• Aproximadamente 6,5 horas (con cargador de 18 W)\n<br>• Aproximadamente 4,5 horas (con cargador de 45 W y el cable de carga incluido)"}
  ,
  {"product_id":"7956276347115","ingramPartNumber":"5688920","xiaomiSku":"34289","body_html":"<br>• Experiencia de triple banda ultrarrápida\n<br>• 12 amplificadores de señal independientes\n<br>• Procesador insignia de seis núcleos Qualcomm\n<br>• Puerto Ethernet de 2,5 Gbps\n<br>• Puerto USB 3.0 de velocidad ultrarrápida<br>• Dimensiones L. × An. × Al. (por unidad): 270 mm × 270 mm × 174 mm\n<br>• Color del producto: Negro\n<br>• Procesador: CPU IPQ8072 A53 de cuatro núcleos a 2,2 GHz Qualcomm®\n<br>• Unidad de procesamiento de red: NPU de doble núcleo de 1,7 GHz\n<br>• Memoria: 1 GB\n<br>• Wi-Fi 2,4G: 4 × 4 (admite hasta el protocolo IEEE 802.11ax, la velocidad máxima teórica es de 1148 Mbps)\n<br>• Wi-Fi de 5 GHz-1: 4 × 4 (admite hasta el protocolo IEEE 802.11ax, la velocidad máxima teórica es de 4804 Mbps)\n<br>• Wi-Fi de 5 GHz-2: 4 × 4 (admite hasta el protocolo IEEE 802.11ax, la velocidad máxima teórica es de 2402 Mbps)\n<br>• Antenas: Antena externa de alta ganancia + antena AIoT interna\n<br>• Disipación del calor: Refrigeración activa\nTotal de puertos:\n- 1 puerto WAN/LAN adaptable de 10/100/1000/2500 Mbps (MDI/MDIX automático)\n- 1 puerto WAN/LAN adaptable de 10/100/1000 Mbps (MDI/MDIX automático)\n- 3 puertos LAN adaptables de 10/100/1000 Mbps (MDI/MDIX automático)\n<br>• Luz indicadora de LED\n8 luces, que incluyen: 1 indicador del sistema, 1 indicador de Internet, 5 puertos de red y 1 luz ambiental\n<br>• Botón de restablecimiento del sistema:1\n<br>• Puerto USB 3.0: 1\n<br>• Botón de red de malla: 1\n<br>• Botón de encendido: 1\n<br>• Puerto de entrada de alimentación: 1\n<br>• Estándares de protocolo IEEE 802.11a/b/g/n/ac/ax，IEEE 802.3/3u/3ab\n<br>• Sistema operativo: MiWiFi ROM, un sistema operativo de router inteligente basado en OpenWRT\n<br>• Cifrado Wi-Fi: Cifrado WPA-PSK/WPA2-PSK/WPA3-SAE,\ncontrol de acceso inalámbrico (lista blanca y negra), SSID oculto\n<br>• Aplicaciones de gestión: Compatible con web, Android e iOS"}
  ,
  {"product_id":"7956276773099","ingramPartNumber":"5688913","xiaomiSku":"31492","body_html":"<br>• Portátil\n<br>• Batería de 30 minutos de duración\n<br>• Motor sin escobillas\n<br>• Eliminación de polvo con un toque<br>• Dimensiones: 267 × 55 × 55 mm\n<br>• Peso neto: Aproximadamente 0,5 kg (unidad principal)\n<br>• Tensión nominal: 10,8 V⎓\n<br>• Potencia nominal: 40 W"}
  ,
  {"product_id":"7956276805867","ingramPartNumber":"5688917","xiaomiSku":"33663","body_html":"<br>• Potente ventilador de succión de 2700 Pa\n<br>• Fregado a presión mejorado\n<br>• Funciones interactivas inteligentes mejoradas\n<br>• Batería de hasta 110 minutos de duraciónUnidad Principal:\n<br>• Dimensiones del producto: 353 x 350 x 81 mm\n<br>• Color: Blanco\n<br>• Peso neto del producto: 3,6 kg\n<br>• Conectividad inalámbrica: Wi-Fi lEEE 802.11b/g/n de 2,4 GHz\n<br>• Tensión nominal:  14,4 V\n<br>• Potencia nominal:  40 W\n<br>• Batería: 2900 mAh (capacidad nominal)/3200 mAh (capacidad nominal)\nBase de carga\n<br>• Dimensiones del producto: 130 x 126 x 93 mm\n<br>• Entrada nominal: 100-240 V~50/60 Hz 0,5 A\n<br>• Salida nominal: 19,8 ⎓1 A\n\n<br>• Sensor de desnivel: Para detectar desniveles y hacer que el dispositivo dé media vuelta\n<br>• Sensor óptico de seguimiento: Para calcular el kilometraje del dispositivo\n<br>• Sensor de navegación visual: Para navegar y posicionar el dispositivo\n<br>• Sensor de desaceleración por infrarrojos:\nPara detectar obstáculos delante del dispositivo"}
  ,
  {"product_id":"7956276838635","ingramPartNumber":"5688942","xiaomiSku":"38951","body_html":"<br>• Compatible con audio inalámbrico de alta resolución\n<br>• Calidad de sonido Hi-Fi\n<br>• Anulación de ruido activa de hasta 43 dB\n<br>• Tecnología mejorada para reducir el ruido del viento\n<br>• Batería de hasta 36 horas de duración\n<br>• Escucha hasta 2 horas de música con una carga de 5 minutos\n<br>• Conectividad inteligente con dos dispositivos\n<br>• Anulación de ruido para llamadas con tres micrófonos<br>• Parámetros de entrada de los auriculares: 5,25 V ⎓ 160 mA como máximo（un solo auricular）\n<br>• Parámetros de entrada del estuche de carga: 5 V ⎓ 0,5 A como máximo\n<br>• Puerto de carga: Tipo C\n<br>• Conectividad inalámbrica: Bluetooth® 5.3\n<br>• Protocolos Bluetooth: Bluetooth® Baja Energía/HFP/A2DP/AVRCP\n<br>• Distancia de funcionamiento: 10 m (espacio abierto sin obstáculos)\n<br>• Impedancia del altavoz: 24 Ω"}
  ,
  {"product_id":"7956276871403","ingramPartNumber":"5688926","xiaomiSku":"35131","body_html":"<br>• Activada por movimiento y de gran alcance, la luz se enciende en cuanto entras a un espacio oscuro\n<br>• Rotación de 360°\n<br>• Batería de 17 meses de duración si se utiliza únicamente como sensor\n<br>• Detección de movimiento humano o animal\n<br>• Detección de las condiciones de luz ambiental\n<br>• Conéctala a una serie de dispositivos inteligentes a través de Bluetooth<br>• Temperatura de funcionamiento: De -10 °C a 40 °C\n<br>• Dimensiones del producto: Φ 80 x 62 mm\n<br>• Tensión nominal: 4,5 V⎓\n<br>• Potencia nominal: 0,35 W\n<br>• Flujo luminoso: 2,5 — 25 lm\n<br>• Sistemas compatibles: Android 4.4 e iOS 9.0 o versiones posteriores"}
  ,
  {"product_id":"7956276904171","ingramPartNumber":"5688897","xiaomiSku":"24792","body_html":"<br>• Carga flash de gran potencia de 20W\n<br>• Suficientemente rápido incluso para un viaje corto\n<br>• Se agarra a tu teléfono de forma automática tan pronto como lo toca\n<br>• Protección de doble refrigeración añadida\n<br>• Aumento de la eficiencia de la disipación térmica\n<br>• Compatibilidad inteligente\n<br>• Funciona con diferentes modelos\nde teléfono<br>• Tipo de puerto: USB-C\n<br>• Entrada: 5V/3A, 9V/2A, 12V/2A, 15V/1.8A, 20V/1.35A\n<br>• Salida: 20W MAX\n<br>• Materiales: PC + Vidrio\n<br>• Dimensiones del producto: 117.2 × 73.4 × 91.7mm\n<br>• Normas aplicadas: T/CA 101-2018\nQ/320281DHR05"}
  ,
  {"product_id":"7956276936939","ingramPartNumber":"5688938","xiaomiSku":"37504","body_html":"<br>• Mopa con vibración sónica de alta frecuencia10 000 vibraciones/min para eliminar fácilmente las manchas\n<br>• Toda la unidad vibra mientras friega\n<br>• Cobertura completa del suelo sin pasar por alto ni una mancha\n<br>• Diseñado específicamente para suelos domésticos\n<br>• Eliminación potente de manchas persistentes<br>• Dimensiones de la unidad principal: 353–96,5 mm\n<br>• Tensión nominal: 14,4 V ⎓\n<br>• Capacidad de la batería nominal: 5200 mAh\n<br>• Potencia nominal: 35,6 W\n<br>• Tensión de carga: 20 V ⎓\n<br>• Peso neto del producto: 3,6 kg\nBase de Carga:\n<br>• Entrada nominal: 100-240 V, 50/60 Hz, 0,8 A\n<br>• Dimensiones de la base de carga: 150 × 80,5 × 101mm\n<br>• Salida nominal: 20 V⎓1,8 A"}
  ,
  {"product_id":"7956277002475","ingramPartNumber":"5688921","xiaomiSku":"34370","body_html":"<br>• Mopa con vibración sónica de alta frecuencia10 000 vibraciones/min para eliminar fácilmente las manchas\n<br>• Toda la unidad vibra mientras friega\n<br>• Cobertura completa del suelo sin pasar por alto ni una mancha\n<br>• Diseñado específicamente para suelos domésticos\n<br>• Eliminación potente de manchas persistentes<br>• Dimensiones de la unidad principal: 353–96,5 mm\n<br>• Tensión nominal: 14,4 V ⎓\n<br>• Capacidad de la batería nominal: 5200 mAh\n<br>• Potencia nominal: 35,6 W\n<br>• Tensión de carga: 20 V ⎓\n<br>• Peso neto del producto: 3,6 kg\nBase de Carga:\n<br>• Entrada nominal: 100-240 V, 50/60 Hz, 0,8 A\n<br>• Dimensiones de la base de carga: 150 × 80,5 × 101mm\n<br>• Salida nominal: 20 V⎓1,8 A"}
  ,
  {"product_id":"7956277035243","ingramPartNumber":"5688911","xiaomiSku":"30802","body_html":"<br>• Alimentos más sanos, con menos aceite y bajos en grasa\n<br>• Circulación de aire caliente de 360°\n<br>• Alimentos deliciosos con bajo contenido en grasa y sencilla preparación\n<br>• También es una yogurtera, un deshidratador de frutas, un microondas y un horno eléctrico\n<br>• Temperatura ajustable desde 40 °C hasta 200 °C*\n<br>• Tiempo de funcionamiento continuo durante 24 horas\n<br>• Aprendizaje sencillo incluso para principiantes\nMás fácil con recetas inteligentes\n<br>• Programa previamente tu freidora y tendrás un plato caliente esperándote en casa\n<br>• Pantalla para controlar el estado de cocción en tiempo real\n<br>• Revestimiento antiadherente de doble capa<br>• Tensión nominal: 220-240 V\n<br>• Frecuencia nominal: 50/60 Hz\n<br>• Peso neto: 3,9 kg\n<br>• Peso bruto: 5,2 kg\n<br>• Potencia nominal: 1500 W\n<br>• Volumen nominal: 3,5 l\n<br>• Material de la cesta: Metal aclad"}
  ,
  {"product_id":"7956277100779","ingramPartNumber":"5688905","xiaomiSku":"28314","body_html":"<br>• Pantalla de temperatura en tiempo real\n<br>• Alta capacidad de 1,5 L\n<br>• Termostato STRIX de Reino Unido \n<br>• Triple protección de seguridad<br>• Dimensiones del producto: 204 × 145 × 235 mm\n<br>• Capacidad: 1.5 L\n<br>• Peso del producto: 1,3 kg\n<br>• Potencia nominal: 1800 W"}
  ,
  {"product_id":"7956277166315","ingramPartNumber":"5688928","xiaomiSku":"35784","body_html":"<br>• Pantalla AMOLED de alta resolución de 1,43\"\n<br>• Más de 200 esferas de reloj\n<br>• Exquisito bisel metálico\n<br>• GPS de doble banda\n<br>• Monitor de oxígeno en sangre durante todo el día\n<br>• Resistencia al agua 5 ATM<br>• Sensores: Sensor de frecuencia cardiaca (con sensor de oxígeno en sangre), acelerómetro, giroscopio, sensor geomagnético, sensor atmosférico y sensor de luz ambiental\n<br>• Dimensiones: 46.5 × 47,3 × 11 mm (sin incluir la correa ni los salientes del contorno)\n<br>• Sistemas de posicionamiento por satélite:\nGPS, GLONASS, GALILEO, BDS y QZSS\n<br>• Estructura:Poliamida reforzada con fibra de vidrio\n<br>• Capacidad de la batería: 470 mAh\n<br>• Pantalla: Pantalla AMOLED de 1,43''\n<br>• Clasificación de resistencia al agua: 5 ATM\n<br>• Resolución: 466 x 466\n<br>• Temperatura de funcionamiento: De -10 °C a 45 °C\n<br>• Correa: Silicona blanca, TPU negro y azul\n<br>• Idioma del sistema: Inglés, alemán, italiano, francés, español, japonés, coreano, neerlandés, portugués, turco, polaco, ucraniano, rumano, checo, griego, ruso, tailandés, vietnamita, portugués brasileño, indonesio, chino tradicional, sueco, finés, noruego y danés\n<br>• Longitud ajustable: 160-220 mm\n<br>• Compatible con: Android 6.0 e iOS 10,0 o versiones posteriores\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11b/g/n 2,4 GHz, Bluetooth 5.2\n<br>• Estándares aplicados: GB 8898-2011, GB 17625.1-2012, GB/T 13837-2012"}
  ,
  {"product_id":"7956277297387","ingramPartNumber":"5688898","xiaomiSku":"24876","body_html":"<br>• La protección dental inteligente adaptada a tus necesidades\n<br>• Motor de levitación magnética de vibración de alta frecuencia\n<br>• Alerta de sobrepresión inteligente para evitar que las encías se lastimen\n<br>• Modos de limpieza personalizados\n<br>• Cepillo con cabezal metálico de acero inoxidable para una limpieza eficiente<br>• Tamaño del mango: L 87.5mm, 28.5mm\n<br>• Voltaje Nominal: 3.7 V\n<br>• Clasificación de la impermeabilidad: IPX7\n<br>• Peso Neto: 110.51g\n<br>• Potencia nominal: 2W\n<br>• Tiempo de carga: 12 Horas\n<br>• Clasificación de la impermeabilidad: IPX7\n<br>• Dimensiones: Muelle de carga cerrado y seguro\n<br>• Método de carga: inductiva\n<br>• Peso neto de muelle de carga: 60g\n<br>• Tamaño del cabezal del cepillo: L 85mm, 24.8mm\n<br>• Material de los cepillos: Cepillo americano DuPont\n<br>• Peso de la cabeza de cepillo: 8g"}
  ,
  {"product_id":"7956277330155","ingramPartNumber":"5688916","xiaomiSku":"33592","body_html":"<br>• Red de malla estable, cobertura Wi-Fi de más de 370 m2\n<br>• Conexión Wi-Fi 6 de doble banda para una experiencia en línea fluida\n<br>• Gran velocidad inalámbrica de hasta 2976 Mbps\n<br>• Conexión fiable para hasta 254 dispositivos<br>• Dimensiones: L. × An. × Al. (por unidad) 97 mm × 97 mm × 222 mm\n<br>• Color del producto: Negro\n<br>• Procesador: CPU Qualcomm® IPQ5000 A53 de doble núcleo a 1,0 GHz\n<br>• Unidad de procesamiento de red: NPU de un solo núcleo de 1,0 GHz\n<br>• Memoria: 256 MB\n<br>• Wi-Fi 2,4G: 2 × 2 (admite hasta el protocolo IEEE 802.11ax; la velocidad máxima teórica es de 574 Mbps)\n<br>• Wi-Fi 5 GHz: 2 × 2 (admite hasta el protocolo IEEE 802.11ax; la velocidad máxima teórica es de 2402 Mbps)\n<br>• Antenas: Antenas de alta ganancia\n<br>• Disipación del calor: Disipación de calor natural\n<br>• Total de puertos: 1 puerto WAN autoadaptable 10/100/1000 Mbps (Auto MDI/MDIX) 3 puertos LAN autoadaptables 10/100/1000 Mbps (Auto MDI/MDIX)\n<br>• Luz indicadora de LED: 2 luces, 1 indicador del sistema y 1 indicador de Internet\n<br>• Botón de restablecimiento del sistema: 1\n<br>• Botón de red de malla: 1\n<br>• Puerto de entrada de alimentación: 1\n<br>• Estándares de protocolo: IEEE 802.11a/b/g/n/ac/ax，IEEE 802.3/3u/3ab\n<br>• Sistema operativo: MiWiFi ROM, un sistema operativo de router inteligente basado en OpenWRT\n<br>• Cifrado Wi-Fi: Cifrado WPA-PSK/WPA2-PSK/WPA3-SAE, control de acceso inalámbrico (lista blanca y negra), SSID oculto\n<br>• Aplicaciones de gestión: Compatible con web, Android e iOS"},
  {"product_id":"7956277362923","ingramPartNumber":"5688945","xiaomiSku":"39500","body_html":"<br>• Gran pantalla AMOLED rectangular de 1,64\"\n<br>• GNSS incorporado\n<br>• Clases guiadas en tu muñeca\n<br>• Más de 110 modos deportivos\n<br>• Batería con una duración de 12 días\n<br>• Monitorización del sueño y monitorización del SpO₂ y de la frecuencia cardiaca durante todo el día\n<br>• Resistencia al agua de 5 ATM\n<br>• Dimensiones: 44,7 mm x 28,8 mm x 11 mm\n<br>• Peso: 20,5 g (sin correa)\n<br>• Pantalla táctil AMOLED de 1,64\"\n<br>• Resolución: 280 x 456 píxeles, 326 ppp\n<br>• Brillo: Hasta 500 nits, ajustable\n<br>• Vidrio templado con revestimiento antihuellas | Vidrio microcurvo de 2,5D\n<br>• Sensores: Sensor de frecuencia cardiaca (con sensor de oxígeno en sangre) | \nAcelerómetro | Giroscopio | Sensor de luz ambiental\n<br>• Tipo de carga: Carga magnética\n<br>• Tiempo de carga: Aproximadamente 60 minutos\n<br>• Tiempo de uso típico: ≥12 días\n<br>• Capacidad: 235 mAh\n<br>• Monitorización de la frecuencia cardiaca\n<br>• Seguimiento del SpO₂\n<br>• Resistencia al agua de 5 ATM\n<br>• Aplicación: Mi Fitness\n<br>• Bluetooth 5.2 BLE\n<br>• Sistema operativo: Android 6.0 o versiones posteriores; iOS 12 o versiones posteriores"}
  ,
  {"product_id":"7956277395691","ingramPartNumber":"5688922","xiaomiSku":"34374","body_html":"<br>• Pantalla impresionante de hasta 120\"\n<br>• Corrección trapezoidal automática multiángulo\n<br>• Las imágenes más nítidas en 1080p\n<br>• Android TV™ con Asistente de Google integrado\n<br>• Entretenimiento con Dolby Audio™<br>• Dimensiones del producto: 115 x 150 x 150 mm\n<br>• Peso neto: 1,3 kg \n<br>• Consumo de energía: Potencia nominal <65 W. Potencia en modo de espera <0,5 W \n<br>• Entrada nominal: Adaptador externo de 19 V-3,42A\n<br>• Tecnología de visualización: Luz LED con tecnología DLP \n<br>• Brillo: 500 lúmenes ANSI\n<br>• Resolución estándar: 1920 × 1080p\n<br>• Relación de proyección: 1,2:1 \n<br>• Tamaño de la pantalla: Entre 60\" y 120\" \n<br>• Enfoque de la lente: Enfoque automático \n<br>• Corrección trapezoidal: Corrección trapezoidal automática multiángulo\n<br>• Almacenamiento integrado: DDR3 de 2 GB/eMMC de 16 GB\n<br>• Sistema operativo: Android TV™\n<br>• Bluetooth: Bluetooth 5.0/BLE \n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11a/b/g/n de 2,4/5 GHz \n<br>• Efectos de audio: *Dolby Audio™\n<br>• Altavoz: Rango completo de 2 x 5 W \n<br>• Nivel de ruido: ≤28 dB(A) a una temperatura ambiente de 25 °C \n<br>• Temperatura/humedad de almacenamiento \nDe -20 a 55 °C/≤90 % \n<br>• Temperatura/humedad de funcionamiento \nDe 0 a 40 °C/De un 20 a un 80 %"}
  ,
  {"product_id":"7956277428459","ingramPartNumber":"5688906","xiaomiSku":"28671","body_html":"<br>• Motor digital de alta velocidad\n<br>• Pantalla HD TFT a color\n<br>• Cepillo inteligente para suelos diferentes tipos de suelo\n<br>• Aspirador y mopa 2 en 1<br>• Dimensiones del producto: 1286 × 214 × 256 mm\n<br>• Peso neto: Aprox. 4,0 kg\n<br>• Capacidad de la batería: 3000 mAh (capacidad nominal)\n<br>• Tensión nominal:25,2 V\n<br>• Potencia nominal:450 W"}
  ,
  {"product_id":"7956277526763","ingramPartNumber":"5688914","xiaomiSku":"31569","body_html":"<br>• Salida de 20 W\n<br>• Compatibilidad smart\n<br>• Compacto y portátil<br>• Tipo de puerto: USB-C\n<br>• Parámetros de entrada: 100-240 V, 50/60 Hz, 0,5 A\n<br>• Parámetros de salida:5 V ⎓ 3 A, 9 V ⎓ 2,22 A, 12 V ⎓ 1,67 A, 20 W máx.\n<br>• Temperatura de funcionamiento: De 0 °C a 40 °C\n<br>• Dimensiones del producto: 38 × 22,2 × 43 mm (longitud de la clavija no incluida)"}
  ,
  {"product_id":"7956277559531","ingramPartNumber":"5688924","xiaomiSku":"34958","body_html":"<br>• Cabezales de afeitado flotantes omnidireccionales\n<br>• Motor de suspensión magnética lineal\n<br>• Burbujas de cavitación sónica de alta frecuencia<br>• Dimensiones del producto: 157 mm de alto × 62,5 mm de ancho × 46 mm de profundidad\n<br>• peso neto: 235g\n<br>• Potencia nominal: 10W\n<br>• Tensión nominal de funcionamiento: 3,7 V ⎓\n<br>• Voltaje de carga nominal: 5V ⎓\n<br>• Tiempo de carga: 2 horas\n<br>• Clasificación impermeable: IPX7"}
  ,
  {"product_id":"7956277592299","ingramPartNumber":"5688903","xiaomiSku":"27105","body_html":"<br>• Superficie flotante para un afeitado más limpio con un diseño cómodo que alivia la presión.\n<br>• Tres cabezales de afeitar flotantes de 360°\n<br>• Tecnología flotante de alivio de presión IFT*\n<br>• Carga tipo C<br>• Número de modelo: S500\n<br>• Dimensiones del producto: 155,1 × 61,6 × 63,3 mm\n<br>• Clasificación de la impermeabilidad: IPX7\n<br>• Entrada nominal: 5 V 1 A\n<br>• Potencia nominal: 3 W\n<br>• Método de carga: Carga tipo C\n<br>• Tiempo de carga: Completamente cargado en 1,5 horas\n<br>• Vida de la batería: 60 minutos\n<br>• Dimensiones del embalaje: 186,2 × 105,5 × 75,1 mm\n<br>• Peso bruto del producto: 345 g"}
  ,
  {"product_id":"7956277625067","ingramPartNumber":"5688901","xiaomiSku":"26922","body_html":"<br>• Puertos de entrada dual\n<br>• Puertos de salida dual\n<br>• Alta capacidad de 74 Wh\n<br>• Carga rápida bidireccional 18-W<br>• Alimentación de la batería: 74 Wh/3,7 V/20.000 mAh\n<br>• Puertos de entrada: Micro-USB/USB-C\n<br>• Parámetros de salida 5V--2,1 A/9V- -2.1A/12V--1,5 A\n<br>• Dimensiones del producto: 154 % 73.6 x 27.3 mm\n<br>• Tipo de batería: Batería de polímero de iones de litio\n<br>• Capacidad nominal: 12.000 mAh (5,1 V/3,6 A)\n<br>• Puertos de salida: 2 x USB-A\n<br>• Parámetros de salida: 5.1 V==-2.4A/9V=-Max. 2 A\n<br>• Parámetro de salida de un solo puerto: 12 V--Máximo. 1.5 A\n<br>• Salida de doble puerto: 5.1 V==3.6 A"}
  ,
  {"product_id":"7956277657835","ingramPartNumber":"5688899","xiaomiSku":"24994","body_html":"<br>• 6 millones de colores\n<br>• Brillo y temperatura de color ajustables\n<br>• Control inteligente<br>• Flujo luminoso: 950 lúmenes\n<br>• Rango de temperatura de color: 1700-6500 K\n<br>• Categoría de bombilla: E27\n<br>• Entrada nominal: 220-240 V~50/60 Hz, 0,07 A\n<br>• Potencia nominal: 9 W\n<br>• Dimensiones: φ55 × 120 mm\n<br>• Vida útil: aprox. 25 000 horas\n<br>• Encendido/apagado: 125 000 ciclos\n<br>• Temperatura de funcionamiento: de -10 °C a 40 °C\n<br>• Humedad de funcionamiento: 0-85 % de humedad relativa\n<br>• Frecuencia de funcionamiento: 2412-2472 MHz\n<br>• Potencia de salida máxima: 17,41 dBm\n<br>• Conectividad inalámbrica: Wi-Fi IEEE 802.11 b/g/n de 2,4 GHz\n<br>• Compatibilidad: Android 4.4, iOS 9.0 o versiones posteriores"}
  ,
  {"product_id":"7956277690603","ingramPartNumber":"5688915","xiaomiSku":"33495","body_html":"<br>• Reproductor streaming en 4K Ultra HD\n<br>• Asistente de Google con Chromecast\n<br>• Con Android 8.1 para una funcionalidad superior<br>• Dimensiones: Altura: 95,25 mm,Anchura: 95,25 mm, Grosor: 16,7 mm, Peso: 147 g\n<br>• Color: Negro\n<br>• Resolución de salida: 4K (3840 x 2160)\n<br>• CPU: Cortex-A53 Quad-core 64 bit\n<br>• GPU: Mali-450\n<br>• RAM: 2 GB DDR3\n<br>• Almacenamientos: 8 GB eMMC\n<br>• Sistema operativo: Android 8.1\n<br>• HDMI 2.0a: 1\n<br>• USB2.0：1\n<br>• Interfaz de alimentación: 1\n<br>• Salida de audio: 1\n<br>• Bluetooth: 4.0"}
  ,
  {"product_id":"7956277723371","ingramPartNumber":"5688774","xiaomiSku":"22002","body_html":"<br>• Google Voice Assistant y Alexa\n<br>• Controla productos Xiaomi desde tu teléfono móvil<br>• Material: PC Resistente al Fuego (Nivel de Resistencia al Fuego V0, Ignífugo 750°)\n<br>• Dimensiones: 90 × 52 × 73\n<br>• Peso (Neto): 115 gramos\ntemperatura de operacion: 0 °C ~ 35 °\n<br>• Potencia nominal: 3680 W (máx.), 50 Hz, μ\nVoltaje/corriente de entrada: 220 – 240 V~, 16 A,\n<br>• Acuerdo WiFi y MHz: Wi -Fi IEEE 802.11 b/g/n 2,4 GHz\n<br>• Plataforma de soporte: Android 4.0 superior, iOS 9.0 superior\n<br>• Aplicación de gestión: Aplicación Xiaomi\n<br>• Botón físico: Un solo clic (enchufe de encendido/apagado de 220 V), pulsación larga (restablecer WiFi )\n<br>• Indicador: Una luz LED: amarilla fija (a partir de ahora), amarilla intermitente (en espera de conexión), azul fija (red conectada), azul intermitente (falla de red o actualización de firmware), luz LED apagada (desconectar 220 V o indicador apagado)"}
  ,
  {"product_id":"7956277756139","ingramPartNumber":"","xiaomiSku":"24034","body_html":"\n<br>• Usando la misma celda de batería que en Tesla,\nBatería de iones de litio de potencia Samsung 18650\ncelda, alcance alrededor de 45 km de rango de conducción para\ndesplazamientos diarios. El paquete de batería aguanta\nen el tubo del bastidor principal, diseño push-pull\nOferta fácil de sacar y poner, puede\ncargar en el muelle o fuera del muelle.\n<br>• Motor sin escobillas de alta velocidad de 250 W El\nMotor poderoso. En comparación con los regulares\nmotor, 250 W de alta velocidad sin escobillas\nEl motor proporciona un par más alto, menos\nresistencia magnética, más rápido\naceleración, más ligero, conducción más fácil\nviento en contra y escalada\nOrdenador de ciclismo\n<br>•Libre para cambiar el modo de energía del asistente con botones\nen pantalla, monitor de actividad de conducción en tiempo real: dinámico\npotencia, velocidad, distancia recorrida, consumo de calorías.\n<br>• Ofrece 4 modos de ciclismo, simplemente puede cambiar con\nbotones en el ciclocomputador. Cada modo con\nRelación de potencia de asistente diferente, libre de cambiar\nsegún la voluntad del jinete. (* Basado en la potencia del pedal =\n60W)\n<br>•Módulo de monitoreo de actividad de ciclismo incorporado, puede\nmuestra la velocidad en tiempo real, la distancia del viaje, la potencia del pedal,\nconsumo de calorías, te ayuda a progresar\nTodos los días, haz que la vida sea maravillosa y más divertida.\nTecnología\n<br>•SHIMANO Nexus Shift Easy-Ride cuando está fuera de\nEnergía. Equipado con Shimano Nexus interior 3-\nOferta de sistema de velocidad \"Fácil\", \"Estándar\", \"Rápido\"\nmodo. Con combinación de asistente eléctrico,\nhacer que el ciclismo sea más fácil, más agradable, más fácil de montar\nmientras la batería está agotada.\n<br>•Sensor de par TMM4. El sensor de par\nmonitorear la fuerza del pedal y entender su\nintención mientras conduce, conduzca el motor para proporcionar\npoder asistente adecuado a su voluntad, hacer paseo\nmás fácil y agradable.\n<br>• Peso: 14,5 kg\n<br>• Rango de viaje: 45 kilometros\n<br>• Máxima velocidad: 25 km/h\n<br>• Fuerza de motor: 250w 36v 15A\n<br>• Tamaño de la rueda: 16 pulgadas\n<br>• Monitor: LCD de 1,8 pulgadas\n<br>• Sensor: Sensor de par del eje central\n<br>• Capacidad de la batería: 5,8Ah 36V\n<br>• Corriente de salida máxima/tiempo\nMáximo continuo: 15A/5min\ncorriente de descarga: 10 A\n<br>• Temperatura de carga: 0℃~+45℃\n<br>• Temperatura de descarga: -20℃~+60℃\n<br>• Cargador:42v 2A"}
  
  ]